version: "3.7"
services:
  nginx_proxy:
    image: nginx_proxy:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_eolymp_proxy
    volumes:
      - ./eolymp_allowlist.conf:/usr/local/nginx/conf/nginx.conf
    environment:
      - TZ=Etc/UTC
    restart: always
